"""Generated by prepare_claymore.py; run only through Blender MCP."""
import bpy
import json
data = json.loads(r'''__DATA__''')
ROOT = '/Users/king/socom'
bpy.ops.wm.read_homefile(use_empty=True)
materials = {}
for key, spec in data['materials'].items():
    mat = bpy.data.materials.new(spec['name'])
    mat.use_nodes = True
    shader = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
    shader.inputs['Roughness'].default_value = .85
    tex = mat.node_tree.nodes.new('ShaderNodeTexImage')
    tex.image = bpy.data.images.load(spec['image'], check_existing=True)
    tex.image.filepath = bpy.path.relpath(spec['image'], start=ROOT + '/art/blender')
    mat.node_tree.links.new(tex.outputs['Color'], shader.inputs['Base Color'])
    materials[key] = mat
for spec in data['meshes']:
    mesh = bpy.data.meshes.new(spec['name'])
    mesh.from_pydata(spec['vertices'], [], spec['faces'])
    mesh.update()
    obj = bpy.data.objects.new(spec['name'], mesh)
    bpy.context.collection.objects.link(obj)
    mesh.materials.append(materials[spec['material']])
    layer = mesh.uv_layers.new(name='UVMap')
    for loop in mesh.loops:
        layer.data[loop.index].uv = spec['uv'][loop.vertex_index]
bpy.context.scene['source'] = data['source']
bpy.context.scene['metres_per_source_unit'] = .1
bpy.ops.wm.save_as_mainfile(filepath=ROOT + '/art/blender/' + data['name'] + '.blend')
